name: web_http
description: A web HTTP client focused on speed and correctness.
version: 0.0.1
homepage: https://github.com/jonahwilliams/web_http
author: Jonah Williams <jonahwilliams@google.com>

dev_dependencies:
  test: '^0.12.0'

environment:
  sdk: '^2.0.0-dev'

transformers:
  - test/pub_serve:
      $include: test/**_test.dart