name: web_http
description: A web HTTP client focused on speed and correctness.
version: 0.0.1
homepage: https://github.com/jonahwilliams/web_http
author: Jonah Williams <jonahwilliams@google.com>

environment:
  sdk: '^2.0.0-dev'
